### ISSUE TITLE
Magisk: build fails when including Magisk in vendorsetup.sh

### ISSUE THREAD

**Issue by 2lucem2** [sfX-android/android_vendor_extendrom#36]
# Description

I am trying to build LineageOS 20 for Sony Xperia XZ1 Compact (lilac) with Magisk included. These are the files:

```bash
cat device/sony/lilac/device.mk 
### PLATFORM
$(call inherit-product, device/sony/yoshino-common/platform.mk)
### PROPRIETARY VENDOR FILES
$(call inherit-product, vendor/sony/lilac/lilac-vendor.mk)

ifeq ($(WITH_FDROID),true)
$(call inherit-product, vendor/fdroid/fdroid-vendor.mk)
endif
ifeq ($(WITH_MICROG),true)
$(call inherit-product, vendor/microg/microg-vendor.mk)
endif

DEVICE_PATH := device/sony/lilac

# Soong
PRODUCT_SOONG_NAMESPACES += \
    $(DEVICE_PATH)

# Device uses high-density artwork where available
PRODUCT_AAPT_CONFIG := normal
PRODUCT_AAPT_PREBUILT_DPI := xhdpi hdpi
PRODUCT_AAPT_PREF_CONFIG := xhdpi

DEVICE_PACKAGE_OVERLAYS += \
    $(DEVICE_PATH)/overlay

### POWER
TARGET_USE_CUSTOM_POWERHINT := true

include $(DEVICE_PATH)/device/*.mk

# Enable extendrom
$(call inherit-product-if-exists, vendor/extendrom/config/common.mk)
```

```bash
cat device/sony/lilac/vendorsetup.sh 
########### extendrom section ###########
export ENABLE_EXTENDROM=true
export EXTENDROM_PREROOT_BOOT=true
export EXTENDROM_PACKAGES="Magisk AuroraStore AuroraServices"

$PWD/vendor/extendrom/er.sh
```

`source build/envsetup.sh` runs without any problems. I can see Magisk being downloaded:

```bash
[download_package] ... downloading package: Magisk.v26.3.apk
[get_packages] ... target package: /speicher/android/lineage/vendor/extendrom/prebuilt/Magisk.apk
…
[MAGISK] Injecting Magisk patcher ended with 0
[MAGISK] ... Magisk found!
[MAGISK] ... MAGISK_TARGET_ARCH specified as arm64
[MAGISK] preparing root finished
```

However, building fails at finishing the build rules:

```bash
finishing build rules ...
FAILED: 
build/make/core/main.mk:1312: warning:  device/sony/lilac/lineage_lilac.mk includes non-existent modules in PRODUCT_PACKAGES
Offending entries:
Magisk
build/make/core/main.mk:1312: error: Build failed.
17:14:16 ckati failed with: exit status 1
```

`device/sony/lilac/lineage_lilac.mk` is inheriting `device/sony/lilac/device.mk`, which is inheriting `vendor/extendrom/config/common.mk`, which populates `PRODUCT_PACKAGES` (`PRODUCT_PACKAGES += $(EXTENDROM_PACKAGES)`) as set per `device/sony/lilac/vendorsetup.sh` (see above)

# Optional information

- device tree: [android_device_sony_lilac](https://github.com/whatawurst/android_device_sony_lilac)
- custom OS: [LineageOS manifest](https://github.com/LineageOS/android/blob/lineage-20.0/default.xml)

# Required(!) information

- custom OS name you build for: `LOS`
- Android version: `A13`
- [COMPLETE(!!!) output when executing: `vendor/extendrom/er.sh`.](https://gist.github.com/2lucem2/50a904392d668cd91ef120cd1c7c1efd)

**Comment by ztmzzz** [comment]
A workaround is to remove these codes in `config/common.mk`.
```
ifdef EXTENDROM_PACKAGES
PRODUCT_PACKAGES += $(EXTENDROM_PACKAGES)
endif
```
I think the part about Magisk in PRODUCT_PACKAGES should be ignored, just as Magisk is ignored when generating the Makefile.

**Comment by 2lucem2** [comment]
That resolved the issue. Build completed with Magisk included and boot image Patched/pre-rooted.

**Comment by 2lucem2** [comment]
The build went through, but neither was Magisk included nor was the boot image patched/pre-rooted (flashed the wrong image in my previous comment. Sorry about that).

**Comment by ztmzzz** [comment]
This is my build sequence. This works for me.
1. withdrew commit [0739ea9](https://github.com/sfX-android/android_vendor_extendrom/commit/0739ea9f1de663dddd9d4bec369da0f3eeae93dd)
2. `source build/envsetup.sh`
3. change `config/common.mk`
4.  `source build/envsetup.sh`
5. `breakfast` and later commands

**Comment by steadfasterX** [comment]
The prob is that it seems to differ depending on how we call it. In my automation setup it works that way but not in your scenario.

Could you share the output of extendrom when not reverting that commit please?

**Comment by 2lucem2** [comment]
@steadfasterX I'm not sure whether you're adressing @ztmzzz or me.

This is the output of extendrom without modifying upstream: https://gist.github.com/2lucem2/51a8ba7523e971a8e20bab87ea7fa11d#file-without-modifications

This is the output after creating the following symlink: `vendor/extendrom/config/magisk/aosp -> lineage`: https://gist.github.com/2lucem2/51a8ba7523e971a8e20bab87ea7fa11d#file-created-symlink

This is the output after reverting commig https://github.com/sfX-android/android_vendor_extendrom/commit/0739ea9f1de663dddd9d4bec369da0f3eeae93dd: https://gist.github.com/2lucem2/51a8ba7523e971a8e20bab87ea7fa11d#file-reverted-commit

**Comment by steadfasterX** [comment]
@2lucem2 sorry that was meant for @ztmzzz ..

anyways dor YOUR issue I would need the build log (in its whole or at least at the end where the images are tight together (and the magisk patching happens).

**Comment by ztmzzz** [comment]
@steadfasterX I use fedora 38 building LOS 20. Sorry I've deleted the source code so I can't give the output of extendrom, but I know why the error occurs. The reason is `$SRC_TOP` for me is `./`, but `$MY_DIR` is fullpath like `/home/xxxxxx`.

**Comment by steadfasterX** [comment]
@2lucem2 
back to the OP: your problem why you created this issue should be solved now.
could you pls test again now (latest extendrom code)?

regarding the other issue (magisk is not there) open another issue and provide the build log please

**Comment by 2lucem2** [comment]
Thanks for the effort. Unfortunately, the issue remains (and, more strangely, now also "AuroraServices" and "AuroraStore" are listed as offending entries, although they didn't cause trouble before).

Here are the logs:
extendrom log: https://gist.github.com/2lucem2/f86b8fd7fc2955b71ed931161e7af9c9#file-extendrom-log
lunch log: https://gist.github.com/2lucem2/f86b8fd7fc2955b71ed931161e7af9c9#file-lunch-log
verbose build log: https://gist.github.com/2lucem2/f86b8fd7fc2955b71ed931161e7af9c9#file-verbose-log

**Comment by steadfasterX** [comment]
oh my.. sorry, pls try again now (the missing aurora etc should be fixed)

**Comment by 2lucem2** [comment]
Now I'm back at square one. Magisk is still making problems. Logs:
extendrom: https://gist.github.com/2lucem2/bb7d4df3d9199dc8bb7c728f549651c1#file-extendrom
lunch: https://gist.github.com/2lucem2/bb7d4df3d9199dc8bb7c728f549651c1#file-lunch
build: https://gist.github.com/2lucem2/bb7d4df3d9199dc8bb7c728f549651c1#file-build-log

**Comment by steadfasterX** [comment]
many thanks for the logs! could you pls retry on latest extendrom code?

**Comment by 2lucem2** [comment]
Sadly, the problem persists. Here are the logs:
extendrom: https://gist.github.com/2lucem2/dd7a2420127647743b05695900b2dfb0#file-extendrom-log
lunch: https://gist.github.com/2lucem2/dd7a2420127647743b05695900b2dfb0#file-lunch-log
build: https://gist.github.com/2lucem2/dd7a2420127647743b05695900b2dfb0#file-verbose-build-log
Many thanks for continuing to look into this issue.

**Comment by steadfasterX** [comment]
no no thx for **your** _patience_ here ;)

could you pls try this:

replace [this line](https://github.com/sfX-android/android_vendor_extendrom/blob/main/config/common.mk#L19C26-L19C54) by: 
`PRODUCT_PACKAGES += $(shell echo $$EXTENDROM_PACKAGES | sed "s/Magisk//g")`

actually I am not sure if the build process allows that at this stage.. but lets see.. ofc this is a workaround only but I really wonder why it isn't working at all for you (while it does for me). 

so you always do this order:

1. source  build/envsetup.sh
2. lunch
3. build

correct? 

and you do not have any other occurrences of EXTENDROM_PACKAGES in any other places (`grep -r EXTENDROM_PACKAGES device/`)?

**Comment by 2lucem2** [comment]
Modified `config/common.mk`:
```bash
cat vendor/extendrom/config/common.mk
##################################################################
# backwards compat for at least A9 where the environment vars
# do not get parsed and become build flags automatically

ifeq ($(EXTENDROM_BOOT_DEBUG),)
EXTENDROM_BOOT_DEBUG := $(shell echo $$EXTENDROM_BOOT_DEBUG)
endif
ifeq ($(EXTENDROM_PREROOT_BOOT),)
EXTENDROM_PREROOT_BOOT := $(shell echo $$EXTENDROM_PREROOT_BOOT)
endif
ifeq ($(EXTENDROM_SIGNATURE_SPOOFING),)
EXTENDROM_SIGNATURE_SPOOFING := $(shell echo $$EXTENDROM_SIGNATURE_SPOOFING)
endif

##################################################################
# Custom packages

ifdef EXTENDROM_PACKAGES
PRODUCT_PACKAGES += $(shell echo $$EXTENDROM_PACKAGES | sed "s/Magisk//g")
endif

##################################################################
# enable gesture support in /e/ OS
# DEPRECATED?!

ifeq ($(EOS_GESTURES),true)
# set specific overlay
DEVICE_PACKAGE_OVERLAYS += \
    vendor/extendrom/overlays/gestures
# build TrebuchetQuickStep (get_prebuilts.sh must be executed once at least)
PRODUCT_PACKAGES += eOSTrebuchetQuickStep
endif

##################################################################
# Signature spoofing overlays

ifeq ($(EXTENDROM_SIGNATURE_SPOOFING),true)
DEVICE_PACKAGE_OVERLAYS += \
    vendor/extendrom/overlays/sigspoof
endif

##################################################################
# extendrom vendor makefile

$(call inherit-product, vendor/extendrom/er.mk)
```

`$EXTENDROM_PACKAGES`is not set elsewhere:
```bash
grep -r EXTENDROM_PACKAGES device/
device/sony/lilac/vendorsetup.sh:export EXTENDROM_PACKAGES="Magisk AuroraStore AuroraServices"
```


`repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc)`
`source build/envsetup.sh`: https://gist.github.com/2lucem2/02bbb2bdd14151692d197fe558ca79d9#file-source-build_envsetup-sh
`lunch lineage_lilac-userdebug`: https://gist.github.com/2lucem2/02bbb2bdd14151692d197fe558ca79d9#file-lunch-lineage_lilac-userdebug
`make -j$(nproc) bacon` verbose.log: https://gist.github.com/2lucem2/02bbb2bdd14151692d197fe558ca79d9#file-make-j-nproc-bacon-verbose-log

Now with an entirely new error (line 816):
`error: ninja: 'user-keys/shared.pk8', needed by 'out/target/product/lilac/obj/APPS/AuroraServices_intermediates/package.apk', missing and no known rule to make it`

**Comment by steadfasterX** [comment]
Ok great so we can use _sed_ here! So this can be solved. Still no idea why that happens for you and not for me . It seems it is not able to overwrite the EXTENDROM_PACKAGES environment variable. Weird but it must be smth in your setup preventing doing so. 

anyways. I need to find out a better handling for the above workaround but lets keep it like that for the moment.

The new error is bc extendrom expects you sign your OS with your own keys. For this the path `<android source>/user-keys` is used and must include your signing keys.

If you do not (want to) sign your OS with your own keys (which is a big security hole..) you can just create keys for signing extendrom packages like this:

1. Clone https://github.com/sfX-android/android_buildtools
1. Follow https://github.com/sfX-android/android_buildtools/tree/main/sign#sign_generate_keyssh to generate new keys

If you want to sign the OS you might wanna also follow https://github.com/sfX-android/android_buildtools/tree/main/sign#sign_set_keysdirsh

(That both signing setup options will also be included one day in extendrom..)

**Comment by 2lucem2** [comment]
> So this can be solved.

Great to hear!

> The new error is bc extendrom expects you sign your OS with your own keys. For this the path `<android source>/user-keys` is used and must include your signing keys.

Of course I want to sign my build with my own keys. I will look into your instructions. Thanks.

**Comment by 2lucem2** [comment]
Now the build completes. AuroraStore and AuroraServices are added. Magisk is *not*, however; also, the boot image has not been pre-rooted. Attached you find the verbose build log: 
https://gist.github.com/2lucem2/34421d511fac1b85b07ffbf5fe9705ce

(The build is still being signed with public keys despite generating my own keys and setting the keysdir using your scripts; but that is another issue entirely.)

**Comment by 2lucem2** [comment]
Opened a pull request: https://github.com/sfX-android/android_vendor_extendrom/pull/40

**Comment by steadfasterX** [comment]
@2lucem2 could you test on your site with the branch "testing_dirhell" if everything is still working as expected there? I needed to change the way how to apply the filter..

**Comment by steadfasterX** [comment]
Wasnt sure if you will be able to test . After testing it for several devices I merged it into main already but pls try on your site!
