### ISSUE TITLE
magisk: patch file does not apply correctly on A9

### ISSUE THREAD

**Issue by steadfasterX** [sfX-android/android_vendor_extendrom#38]
# Description

splitted from #35

# Required(!) information

- Android version: `A9`

```
building image from target_files BOOT...
Traceback (most recent call last):
File "build/make/tools/releasetools/make_recovery_patch", line 55, in
main(sys.argv[1:])
File "build/make/tools/releasetools/make_recovery_patch", line 42, in main
input_dir, "BOOT")
File "/home/clawdev/A9/build/make/tools/releasetools/common.py", line 577, in GetBootableImage
info_dict, has_ramdisk, two_step_image)
File "/home/clawdev/A9/build/make/tools/releasetools/common.py", line 516, in _BuildBootableImage
RunAndCheckOutput(mpatcher, verbose=True, env={'system_root_image': info_dict.get("system_root_image", "false")})
NameError: global name 'RunAndCheckOutput' is not defined

```

# Note

_when sharing logs or longer texts it is strongly recommended 
using [github gists](https://gists.github.com)_

**Comment by ClawOfDead** [comment]
Yes I understand I'm currently new on Github didn't know about this gists thing. Did you find something about the error on A9?

**Comment by steadfasterX** [comment]
fixed by https://github.com/sfX-android/android_vendor_extendrom/commit/29a55a0a98197c4ff69faed4c9da9beccc002ef7

**Comment by ClawOfDead** [comment]
hey, 
I tried compiling today and still have the same error as before (I redownloaded all the repo btw) + I had to change $TopDir/$MyDir to $MyDir because of duplicate app and still the same error at 99% RunAndCheckOutput(mpatcher, verbose=True, env={'system_root_image': info_dict.get("system_root_image", "false")})
NameError: global name 'RunAndCheckOutput' is not defined

**Comment by steadfasterX** [comment]
the SRC_DIR issue had been [fixed](https://github.com/sfX-android/android_vendor_extendrom/commit/0739ea9f1de663dddd9d4bec369da0f3eeae93dd) a couple of minutes ago . are you sure you had reset the whole sources? it looks like the old patch is still applied. ensure you reset `build/make` first and remove `vendor/extendrom/config/magisk/lineage/A9/EXTENDROM_PATCHER_DONE`

**Comment by ClawOfDead** [comment]
Yes I made a make clean

**Comment by steadfasterX** [comment]
make clean does not reset the sources. you need to do at least what I said. so e.g:

```
repo forall build/make vendor/extendrom -c "git reset --hard"
rm vendor/extendrom/config/magisk/lineage/A9/EXTENDROM_PATCHER_DONE
repo sync build/make vendor/extendrom
```

**Comment by steadfasterX** [comment]
I need the **full** output of extendrom always, please. use gists to provide those

**Comment by ClawOfDead** [comment]
https://gist.github.com/ClawOfDead/c8caa64f1895faa5903ffa2a61e77189

**Comment by steadfasterX** [comment]
thx. the reason why the patch cannot be found is: https://gist.github.com/ClawOfDead/c8caa64f1895faa5903ffa2a61e77189#file-gistfile1-txt-L21
this is usually "lineage" or "axp". 

please ensure you follow the process briefly: https://github.com/sfX-android/android_vendor_extendrom/wiki/Setup#vendorsetupsh

you missed the lunch command after sourcing build/envsetup

**Comment by ClawOfDead** [comment]
Someone told me to just "cp -R /home/clawdev/A9/vendor/extendrom/config/magisk/lineage /home/clawdev/A9/vendor/extendrom/config/magisk/a95xf1" Because the build we using isn't a regular one..

**Comment by steadfasterX** [comment]
Could you pls share the output of your lunch command?

**Comment by ClawOfDead** [comment]
lunch a95xf1-userdebug
hardware/amlogic/wifi/configs/wifi.mk:43: warning: WIFI_MOUDLE is multiwifi
hardware/amlogic/wifi/configs/wifi.mk:47: warning: WIFI_BUILD_IN is false
hardware/amlogic/bluetooth/configs/bluetooth.mk:20: warning: BLUETOOTH_MODULE is BCMBT
hardware/amlogic/bluetooth/configs/bluetooth.mk:24: warning: BLUETOOTH_INF is not set

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=a95xf1
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv7-a-neon
TARGET_2ND_CPU_VARIANT=cortex-a9
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-87-generic-x86_64-Ubuntu-20.04.6-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PSV1.210329.021
OUT_DIR=out
============================================

**Comment by ClawOfDead** [comment]
I tried it like that and it failed with this error on building:
https://gist.github.com/ClawOfDead/69b8dc90eb2294fb63a9b18a8f6038f6

**Comment by steadfasterX** [comment]
Ok thanks. This is not a standard OS it seems. Could you share the build manifest link pls?

**Comment by ClawOfDead** [comment]
I give you all the manifest cause we include OpenGapps also:
https://gist.github.com/ClawOfDead/666386cf09a00be5c378bd9030b75143

**Comment by ClawOfDead** [comment]
this is what I do for building:
source build/envsetup.sh
export ANDROID_BUILD_TYPE=64
export ANDROID_A32_SUPPORT=false
export LC_ALL=C
lunch a95xf1-userdebug
make -j12 otapackage

**Comment by steadfasterX** [comment]
well. the reason why it fails is not the patching anymore. so it seems you had reset the sources successful now.

it also seems you OS is named _a95xf1_ which I can add to extendrom (later if all is working) so you do not need to copy that folder. the thing is that even though it seems that you are running a supported OS (Ubuntu 20.04) it fails [here](https://gist.github.com/ClawOfDead/69b8dc90eb2294fb63a9b18a8f6038f6#file-gistfile1-txt-L516) where the reason is a segfault [here](https://gist.github.com/ClawOfDead/69b8dc90eb2294fb63a9b18a8f6038f6#file-gistfile1-txt-L503).

This command here is what it tries to execute (from within out/.magisk/ dir):

`./magiskboot cpio ramdisk.cpio "add 0750 $INIT magiskinit" "mkdir 0750 overlay.d" "mkdir 0750 overlay.d/sbin" "$SKIP32 add 0644 overlay.d/sbin/magisk32.xz magisk32.xz" "$SKIP64 add 0644 overlay.d/sbin/magisk64.xz magisk64.xz" "add 0644 overlay.d/sbin/stub.xz stub.xz" "patch" "$SKIP_BACKUP backup ramdisk.cpio.orig" "mkdir 000 .backup" "add 000 .backup/.magisk config"`

This fails as you get a core dump / crash when doing so. try that command manually and then check your system logs. e.g.

```
cd out/.magisk
./magiskboot
# (you should see an error message after that one)

journalctl -xe | tail -n 1000 | grep -A100 magiskboot
```

**Comment by ClawOfDead** [comment]
The reason to use 26.2 is because of patch vbmeta only available on this one.. otherwise I need to use recovery mode and I wanted to keep the android recovery. Anyways I will retry maybe with the latest. I will see,

**Comment by steadfasterX** [comment]
wdym by "patch vbmeta" here? if it is in 26.2 it should be in 26.3 as well. anyways the system log will reveal more hopefeully

**Comment by ClawOfDead** [comment]
vbmeta patch to not have to boot everytime to recovery when you don't have ramdisk partition, and sadly it's only on 26.2

**Comment by steadfasterX** [comment]
well then try as I mentioned and use the latest Magisk. if it works with that one we need to find out what they fixed in 26.3 and try to reproduce it. but first you need to test the latest one
